config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/jobs', as: 'sidekiq'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users


  resources :projects, shallow: true do
    member do
      post 'master'
      post 'sync'
    end

    resources :apps do
      member do
        post 'promote'
      end
    end
    resources :branches
    resources :merge_requests do
      member do
        post 'approve'
      end
    end
    resources :builds do
      member do
        post 'stop'
      end
    end
    resources :tests do
      member do
        post 'stop'
      end
    end
    resources :issues
    resources :releases do
      member do
        post 'bump'
        post 'publish'
        post 'rebuild'
        post 'close'
      end
    end
  end

  root to: 'home#index'
end

app/models/branch.rb
class Branch
  include Mongoid::Document
  include Mongoid::Timestamps

  include Nameable

  field :commit, type: String
  field :protected, type: Boolean

  belongs_to :project

  has_one :build, dependent: :destroy
  has_one :test, dependent: :destroy

  has_many :outgoing_merges, class_name: 'MergeRequest', inverse_of: :source_branch
  has_many :incoming_merges, class_name: 'MergeRequest', inverse_of: :target_branch

  validates_uniqueness_of :name, scope: :project


  def category
    ns = name.split('/')
    ns.first if ns.count > 1
  end

  def flat_name
    name.gsub('/', '-')
  end

  def release
    @rc_name ||= name.sub(Release::BRANCH_PREFIX, '')
    @rc ||= project.releases.where(name: @rc_name).first
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_project, only: [:index, :new, :create]
  before_action :set_branch, except: [:index, :new, :create]

  def index
    @branches = @project.branches
    @uncategorized_branches = @branches.reject(&:category)
    @categorized_branches = @branches.select(&:category).group_by(&:category)
    respond_with @branches
  end

  def show
    authorize! :read, @branch
    respond_with @branch
  end

  private
  def set_project
    @project = Project.find(params[:project_id])
    authorize! :read, @project
  end

  def set_branch
    @branch = Branch.find(params[:id])
    @project = @branch.project
  end
end

app/views/branches/_branch.html.slim
= panel do
  .panel-heading
    h3.panel-title
      = icon_w :code_fork, branch.name
      - if branch.protected?
        .pull-right= icon_w(:lock)
  .panel-body
    p
      - build = branch.build
      - if build.present?
        = render 'builds/label', build: build
        - issue = build.issue
        - if issue.present?
          = render 'issues/label', issue: issue
          - if issue.release.present?
            = render 'releases/label', release: issue.release
        - if build.app.present?
          = render 'apps/label', app: build.app

      - test = branch.test
      - if test.present?
        = render 'tests/label', test: test

    ul.list-inline
      - unless build.present?
        li= link_to 'New Build', new_project_build_path(branch.project, branch_id: branch), class: 'btn btn-primary'
      - unless test.present?
        li= link_to 'New Test', new_project_test_path(branch.project, branch_id: branch), class: 'btn btn-primary'

  ul.list-group
    - if branch.outgoing_merges.any?
      li.list-group-item.list-group-item-info title="#{Branch.human_attribute_name(:outgoing_merges)}" data-toggle="tooltip" data-placement="bottom"
        = render partial: 'merge_requests/label', collection: branch.outgoing_merges, as: :merge_request
    - if branch.incoming_merges.any?
      li.list-group-item.list-group-item-warning title="#{Branch.human_attribute_name(:incoming_merges)}" data-toggle="tooltip" data-placement="bottom"
        = render partial: 'merge_requests/label', collection: branch.incoming_merges, as: :merge_request

app/views/branches/_label.html.slim
ruby:
  title ||= Branch.model_name.human
  icon ||= :code_fork

= link_to branch, class: 'label-group', title: title, data: {toggle: 'tooltip', placement: 'top'} do
  = tag_label icon_w(icon), :default
  = tag_label branch.name, :info

app/views/branches/index.html.slim
.row
  - @uncategorized_branches.each do |branch|
    .col-md-3
      = render branch

.row
  - @categorized_branches.each do |category, branches|
    .col-md-3
      .page-header
        h3= category
      = render branches

app/views/branches/show.html.slim
= render @branch