config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/jobs', as: 'sidekiq'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users


  resources :projects, shallow: true do
    member do
      post 'master'
      post 'sync'
    end

    resources :apps do
      member do
        post 'promote'
      end
    end
    resources :branches
    resources :merge_requests do
      member do
        post 'approve'
      end
    end
    resources :builds do
      member do
        post 'stop'
      end
    end
    resources :tests do
      member do
        post 'stop'
      end
    end
    resources :issues
    resources :releases do
      member do
        post 'bump'
        post 'publish'
        post 'rebuild'
        post 'close'
      end
    end
  end

  root to: 'home#index'
end

app/models/build.rb
class Build
  include Mongoid::Document
  include Mongoid::Timestamps

  include Nameable
  include Runnable
  include Queueable
  include Configurable

  field :url, type: String

  belongs_to :branch
  belongs_to :app
  belongs_to :issue, required: false

  validates_format_of :name, with: /\A[0-9a-z-]+\z/

  delegate :project, :protected?,
           to: :branch

  before_destroy :cleanup


  def issue_name
    issue.try(:name)
  end

  def issue_name=(value)
    # find_by cause Mongoid::Errors::DocumentNotFound when Mongoid.raise_not_found_error true
    self.issue = Issue.where(name: value).first
  end

  def run
    return unless can_run?

    RunBuildJob.perform_later(self.id.to_s) unless queued?(RunBuildJob)
  end

  def stop
    return unless super

    StopJobOnBuildServerJob.perform_later(project.id.to_s, job_name)
  end

  def final_config
    (project.config[:BUILD][:CONFIG]||{}).map {|k, v|
      [k, instance_eval(v)]
    }.to_h.merge(config||{})
  end

  def job_name_prefix
    project.config[:JENKINS_PROJECT][:BUILD]
  end

  def job_name
    "#{job_name_prefix}-#{branch.flat_name}"
  end

  def cleanup
    DeleteJobFromBuildServerJob.perform_later(project.id.to_s, job_name)
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_project, only: [:index, :new, :create]
  before_action :set_build, except: [:index, :new, :create]

  def index
    @builds = @project.builds
    @builds = @builds.where(app: @app) if @app.present?
    @builds = @builds.where(branch: @branch) if @branch.present?
    respond_with @builds
  end

  def new
    @build = Build.new
    @build.app = @app if @app.present?
    @build.branch = @branch if @branch.present?
    respond_with @build
  end

  def create
    @build = Build.new(build_params)
    authorize! :create, @build
    @build.run if @build.save

    respond_with @build
  end

  def show
    authorize! :read, @build
    respond_with @build
  end

  def edit
    respond_with @build
  end

  def update
    authorize! :update, @build
    @build.rerun if @build.update(build_params)
    respond_with @build
  end

  def stop
    authorize! :update, @build
    @build.stop
    respond_with @build
  end

  def destroy
    authorize! :destroy, @build
    @build.destroy
    respond_with @build
  end

  private
  def set_project
    @project = Project.find(params[:project_id])
    authorize! :read, @project
    @app = @project.apps.find(params[:app_id]) if params[:app_id].present?
    @branch = @project.branches.find(params[:branch_id]) if params[:branch_id].present?
  end

  def build_params
    params.require(:build).permit!
  end

  def set_build
    @build = Build.find(params[:id])
    @project = @build.project
  end
end

app/views/builds/_build.html.slim
= panel bs_context(build.status), id: "build-#{build.id.to_s}" do
  .panel-heading
    h3.panel-title
      = link_to icon_w(:gavel, build.name), build.url, target: '_blank'
      .pull-right
        - if build.state.running?
          = link_to icon_w(:close), stop_build_path(build), method: :post, remote: true, class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure to stop?', disable_with: 'stopping...'}
        - else
          = link_to icon_w(:trash_o), build, method: :delete, remote: true, class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure to delete?', disable_with: 'deleting...'}
  .panel-body
    ul.list-inline
      li
        a.btn.btn-primary data-toggle="collapse" href="#build-config-#{build.id}"
          = Build.human_attribute_name(:config)
      - if build.can_rerun?
        li= link_to 'Rerun', edit_build_path(build), class: 'btn btn-primary'

    pre.collapse id="build-config-#{build.id}"
      = build.readable_config

    = render 'branches/label', branch: build.branch
    = render 'apps/label', app: build.app
    - issue = build.issue
    - if issue.present?
      = render 'issues/label', issue: issue
      - if issue.release.present?
        = render 'releases/label', release: issue.release

app/views/builds/_form.html.slim
= bootstrap_form_for build, url: (project_builds_path(project) unless build.persisted?) do |f|
  = f.text_field :name
  = f.text_area :readable_config
  = f.collection_select :branch, project.branches.reject {|b| b.build&.persisted? && b.build != build }, :id, :name, {selected: build.branch_id, prompt: true}, {disabled: build.persisted?}
  = f.collection_select :app, project.apps.reject(&:has_build?)|[build.app].compact, :id, :name, selected: build.app_id, prompt: true
  = f.text_field :issue_name, autocomplete: 'off', data: {provide: 'typeahead', source: project.issues.without_state(:done).reject {|b| b.build && b.build.persisted?}.map(&:name)}
  = f.submit

app/views/builds/_label.html.slim
= link_to build, class: 'label-group', title: build.stated, data: {toggle: 'tooltip', placement: 'top'} do
  = tag_label icon_w(:gavel), :default
  = tag_label build.name, bs_context(build.status)

app/views/builds/destroy.js.slim
| target = '#build-#{@build.id}';

- unless @error.present?
  | $(target).remove();

app/views/builds/edit.html.slim
= render 'builds/form', build: @build, project: @project

app/views/builds/index.html.slim
.row
  - Build.state.options.each do |text, value|
    .col-md-3 id="build-state-#{value}"
      .page-header
        h3= text
      = render @builds.with_state(value)

app/views/builds/new.html.slim
= render 'builds/form', build: @build, project: @project

app/views/builds/show.html.slim
.row
  - Build.state.options.each do |text, value|
    .col-md-3 id="build-state-#{value}"
      .page-header
        h3= text
      - if @build.state == value
        = render @build

app/views/builds/stop.js.slim
| target = '#build-#{@build.id}';

- unless @error.present?
  | $(target).remove();
  | $('#build-state-#{@build.state}').append('#{ j( render @build ) }');

app/views/builds/update.js.slim
| $('#build-#{@build.id}').remove();
| $('#build-state-#{@build.state}').append('#{ j( render @build ) }')