config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/jobs', as: 'sidekiq'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users


  resources :projects, shallow: true do
    member do
      post 'master'
      post 'sync'
    end

    resources :apps do
      member do
        post 'promote'
      end
    end
    resources :branches
    resources :merge_requests do
      member do
        post 'approve'
      end
    end
    resources :builds do
      member do
        post 'stop'
      end
    end
    resources :tests do
      member do
        post 'stop'
      end
    end
    resources :issues
    resources :releases do
      member do
        post 'bump'
        post 'publish'
        post 'rebuild'
        post 'close'
      end
    end
  end

  root to: 'home#index'
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  include Nameable
  include Configurable

  field :private, type: Boolean

  has_one :code_manager
  has_one :build_server
  has_one :issue_tracker
  has_one :app_platform


  has_many :branches, dependent: :destroy
  has_many :merge_requests, dependent: :destroy
  has_many :releases, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :apps, dependent: :destroy
  has_many :pipelines, dependent: :destroy

  has_and_belongs_to_many :members, class_name: 'User', inverse_of: nil, after_remove: :remove_master
  has_and_belongs_to_many :masters, class_name: 'User', inverse_of: nil, after_add: :add_member

  validates_uniqueness_of :name


  def builds
    Build.where(:branch_id.in => branch_ids)
  end

  def tests
    Test.where(:branch_id.in => branch_ids)
  end


  def add_member(user)
    self.members << user unless self.members.include?(user)
  end

  def remove_member(user)
    self.members.delete(user) if self.members.include?(user)
  end

  def add_master(user)
    self.masters << user unless self.masters.include?(user)
  end

  def remove_master(user)
    self.masters.delete(user) if self.masters.include?(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = Project.all
    respond_with @projects
  end

  def show
    authorize! :read, @project
    respond_with @project
  end

  def master
    @user = @project.members.find(params[:user_id])
    authorize! :master, @project
    if @project.masters.include?(@user)
      @project.remove_master(@user)
    else
      @project.add_master(@user)
    end
    respond_with @project
  end

  def sync
    @sync_type = params[:type]
    authorize! :master, @project
    case @sync_type
      when 'code_manager'
        @project.code_manager.sync
        @project.code_manager.schedule
      when 'app_platform'
        @project.app_platform.sync
        @project.app_platform.schedule
      when 'issue_tracker'
        @project.issue_tracker.sync
        @project.issue_tracker.schedule
      when 'build_server'
        @project.build_server.sync
        @project.build_server.schedule
      else
        # nothing
    end
    respond_with @project
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_app_platform.html.slim
dl.dl-horizontal#app_platform
  dt= AppPlatform.model_name.human
  dd
    = project.app_platform.try(:name)
    - if project.app_platform.can_sync?
      = link_to icon_w(:refresh), sync_project_path(project, type: :app_platform), method: :post, remote: true, data: {confirm: 'Are you sure to sync?', disable_with: 'processing...'}

app/views/projects/_build_server.html.slim
dl.dl-horizontal#build_server
  dt= BuildServer.model_name.human
  dd
    = project.build_server.try(:name)
    - if project.build_server.can_sync?
      = link_to icon_w(:refresh), sync_project_path(project, type: :build_server), method: :post, remote: true, data: {confirm: 'Are you sure to sync?', disable_with: 'processing...'}

app/views/projects/_code_manager.html.slim
dl.dl-horizontal#code_manager
  dt= CodeManager.model_name.human
  dd
    = project.code_manager.try(:name)
    - if project.code_manager.can_sync?
      = link_to icon_w(:refresh), sync_project_path(project, type: :code_manager), method: :post, remote: true, data: {confirm: 'Are you sure to sync?', disable_with: 'processing...'}

app/views/projects/_issue_tracker.html.slim
dl.dl-horizontal#issue_tracker
  dt= IssueTracker.model_name.human
  dd
    = project.issue_tracker.try(:name)
    - if project.issue_tracker.can_sync?
      = link_to icon_w(:refresh), sync_project_path(project, type: :issue_tracker), method: :post, remote: true, data: {confirm: 'Are you sure to sync?', disable_with: 'processing...'}

app/views/projects/_member.html.slim
= link_to master_project_path(project, user_id: user), method: :post, remote: true, id: "member-#{user.id}", class: 'list-group-item', data: {confirm: 'Are you sure to set/unset master?', disable_with: 'processing...'} do
  = user.name
  - if project.masters.include?(user)
    = badge 'master'

app/views/projects/_project.html.slim
.panel.panel-default id="project-#{project.id}"
  .panel-heading
    h3.panel-title
      = icon_w :suitcase, project.name
      - if project.private?
        .pull-right= icon_w(:lock)
  .panel-body
    = render 'projects/code_manager', project: project
    = render 'projects/app_platform', project: project
    = render 'projects/issue_tracker', project: project
    = render 'projects/build_server', project: project

    a.btn.btn-primary data-toggle="collapse" href="#project-config-#{project.id}"
      = Project.human_attribute_name(:config)

    pre.collapse id="project-config-#{project.id}"
      = project.readable_config
  .list-group
    = link_to project_apps_path(project), class: 'list-group-item' do
      = icon_w :cloud, App.model_name.plural.titlecase
      = badge(project.apps.count)
    = link_to project_branches_path(project), class: 'list-group-item' do
      = icon_w :code_fork, Branch.model_name.plural.titlecase
      = badge(project.branches.count)
    = link_to project_merge_requests_path(project), class: 'list-group-item' do
      = icon_w :code, MergeRequest.model_name.plural.titlecase
      = badge(project.merge_requests.count)
    = link_to project_builds_path(project), class: 'list-group-item' do
      = icon_w :gavel, Build.model_name.plural.titlecase
      = badge(project.builds.count)
    = link_to project_tests_path(project), class: 'list-group-item' do
      = icon_w :flask, Test.model_name.plural.titlecase
      = badge(project.tests.count)
    = link_to project_issues_path(project), class: 'list-group-item' do
      = icon_w :paw, Issue.model_name.plural.titlecase
      = badge(project.issues.count)
    = link_to project_releases_path(project), class: 'list-group-item' do
      = icon_w :flag, Release.model_name.plural.titlecase
      = badge(project.releases.count)
    = link_to "#project-members-#{project.id}", class: 'list-group-item', data: {toggle: 'collapse'} do
      = icon_w :users, Project.human_attribute_name(:members)
      = badge(project.members.count)
  .list-group.collapse id="project-members-#{project.id}"
    = render partial: 'projects/member', collection: project.members, as: :user, locals: {project: project}

app/views/projects/index.html.slim
.row
  - @projects.each do |project|
    .col-md-6
      = render project

app/views/projects/master.js.slim
| target = '#project-members-#{@project.id} #member-#{@user.id}';

- unless @error.present?
  | $(target).replaceWith('#{ j( render 'projects/member', user: @user, project: @project ) }');

app/views/projects/show.html.slim
= render @project

app/views/projects/sync.js.slim
| target = '#project-#{@project.id} ##{@sync_type}';

- unless @error.present?
  | $(target).replaceWith('#{ j( render "projects/#{@sync_type}", project: @project ) }');