config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/jobs', as: 'sidekiq'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users


  resources :projects, shallow: true do
    member do
      post 'master'
      post 'sync'
    end

    resources :apps do
      member do
        post 'promote'
      end
    end
    resources :branches
    resources :merge_requests do
      member do
        post 'approve'
      end
    end
    resources :builds do
      member do
        post 'stop'
      end
    end
    resources :tests do
      member do
        post 'stop'
      end
    end
    resources :issues
    resources :releases do
      member do
        post 'bump'
        post 'publish'
        post 'rebuild'
        post 'close'
      end
    end
  end

  root to: 'home#index'
end

app/views/layouts/_footer.html.slim
= nav_bar fixed: :bottom, brand: icon_w(:copyright, title: t('.copyright'), data: {toggle: 'tooltip', placement: 'top'}), brand_link: 'https://github.com/moonavw/labman', responsive: true do
  = menu_group do
    - if @project.present?
      = menu_item @project.name, project_path(@project)
  = menu_group pull: :right do
    - if can?(:access, :rails_admin)
      = menu_item icon_w(:database), rails_admin_path, target: '_blank'
    - if can?(:manage, :all)
      = menu_item icon_w(:cogs), sidekiq_path, target: '_blank'

    - if Rails.env.development?
      = menu_item icon_w(:terminal), "javascript: $('#console').toggle()"
      css:
        #console {
          bottom: 50px;
          display: none;
        }
      = console

app/views/layouts/_header.html.slim
= nav_bar fixed: :top, brand: icon_w(:magnet, title: t('app'), data: {toggle: 'tooltip', placement: 'bottom'}), responsive: true do
  = menu_group do
    = drop_down icon_w(:suitcase, Project.model_name.plural.titlecase) do
      - Project.all.each do |project|
        = menu_item project.name, project_path(project)
    - if @project.present?
      = menu_item icon_w(:cloud, App.model_name.plural.titlecase), project_apps_path(@project)
      = menu_item icon_w(:code_fork, Branch.model_name.plural.titlecase), project_branches_path(@project)
      = menu_item icon_w(:code, MergeRequest.model_name.plural.titlecase), project_merge_requests_path(@project)
      = menu_item icon_w(:gavel, Build.model_name.plural.titlecase), project_builds_path(@project)
      = menu_item icon_w(:flask, Test.model_name.plural.titlecase), project_tests_path(@project)
      = menu_item icon_w(:paw, Issue.model_name.plural.titlecase), project_issues_path(@project)
      = menu_item icon_w(:flag, Release.model_name.plural.titlecase), project_releases_path(@project)
  = menu_group pull: :right do
    - if signed_in?
      = drop_down icon_w(:user) do
        = menu_item icon_w(:user_o, current_user.name), edit_user_registration_path
        = menu_item icon_w(:sign_out, t('.sign_out')), destroy_user_session_path, method: :delete
    - else
      = menu_item icon_w(:sign_in, t('.sign_in')), new_user_session_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title
      = content_for?(:title) ? yield(:title) : controller_name
      = ' | '
      = t('app')
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      = render 'layouts/header'
    main.container
      = bootstrap_flash
      = yield
    footer
      = render 'layouts/footer'

app/views/layouts/error.js.slim
== yield

| $(target).before('#{ j bootstrap_flash }');